In [1]:
#importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#importing the dataset

data=pd.read_csv("kidney_disease (1).csv")

In [65]:
data


id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0  normal    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0  normal    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...   pcv      wc   rc  htn   dm  cad  appet   pe  ane  \
0    notpresent  ...  44.0  7800.0  5.2  yes  yes   no   good   no   no   
1    notpresent  ...  38.0  6000.0  5.2   no   no   no   good   no   no   
2    notpresent  ...  31.0  7500.0  5.2   no  yes   no   poor   no  yes   
3    notpresent  ...  32.0  6700.0  3.9  yes   no   no   poor  yes  yes   
4    notpresent  ...  35.0  7300.0  4.6   no   no   no   good   no   no   
..          ...  ...   ...     ...  ...  ...  ...  ...    ...  ...  ...   
395  notpresent  ...  47.0  6700.0  4.9   no   no   no   good   no   no   
396  notpresent  ...  54.0  7800.0  6.2   no   no   no   good   no   no   
397  notpresent  ...  49.0  6600.0  5.4   no   no   no   good   no   no   
398  notpresent  ...  51.0  7200.0  5.9   no   no   no   good   no   no   
399  notpresent  ...  53.0  6800.0  6.1   no   no   no   good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [4]:
data.isnull().any() #checking for missing values


id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [5]:
data['pcv']=data['pcv'].replace('?','')
data['wc']=data['wc'].replace('?','')
data['rc']=data['rc'].replace('?','')


In [6]:
data['pcv']=pd.to_numeric(data['pcv'])

In [7]:
data['wc']=pd.to_numeric(data['wc'])

In [8]:
data['rc']=pd.to_numeric(data['rc'])

In [9]:
data['age']=data['age'].fillna(value=data['age'].mean())

In [10]:
data['bp']=data['bp'].fillna(value=data['bp'].mean())

In [11]:
data['sg']=data['sg'].fillna(value=data['sg'].mean())

In [12]:
data['al']=data['al'].fillna(value=data['al'].mean())

In [13]:
data['su']=data['su'].fillna(value=data['su'].mean())

In [14]:
data['rbc']=data['rbc'].fillna(value=data['rbc'].mode().iloc[0])

In [15]:
data['pc']=data['pc'].fillna(value=data['pc'].mode().iloc[0])

In [16]:
data['pcc']=data['pcc'].fillna(value=data['pcc'].mode().iloc[0])

In [17]:
data['ba']=data['ba'].fillna(value=data['ba'].mode().iloc[0])

In [18]:
data['bgr']=data['bgr'].fillna(value=data['bgr'].mean())

In [19]:
data['bu']=data['bu'].fillna(value=data['bu'].mean())

In [20]:
data['sc']=data['sc'].fillna(value=data['sc'].mean())

In [21]:
data['sod']=data['sod'].fillna(value=data['sod'].mean())

In [22]:
data['pot']=data['pot'].fillna(value=data['pot'].mean())

In [23]:
data['hemo']=data['hemo'].fillna(value=data['hemo'].mean())

In [24]:
data['pcv']=data['pcv'].fillna(value=data['pcv'].mode().iloc[0])

In [25]:
data['wc']=data['wc'].fillna(value=data['wc'].mode().iloc[0])

In [26]:
data['rc']=data['rc'].fillna(value=data['rc'].mode().iloc[0])

In [27]:
data['htn']=data['htn'].fillna(value=data['htn'].mode().iloc[0])

In [28]:
data['dm']=data['dm'].fillna(value=data['dm'].mode().iloc[0])

In [29]:
data['cad']=data['cad'].fillna(value=data['cad'].mode().iloc[0])

In [30]:

data['appet']=data['appet'].fillna(value=data['appet'].mode().iloc[0])

In [31]:
data['pe']=data['pe'].fillna(value=data['pe'].mode().iloc[0])

In [32]:
data['ane']=data['ane'].fillna(value=data['ane'].mode().iloc[0])

In [33]:

data['pcv']=pd.to_numeric(data['pcv'])





In [34]:
data.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [35]:
x=data.iloc[:,1:25]

In [36]:
type(x)

pandas.core.frame.DataFrame

In [37]:


x=data.iloc[:,1:25].values

In [38]:
x

array([[48.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [7.0, 50.0, 1.02, ..., 'good', 'no', 'no'],
       [62.0, 80.0, 1.01, ..., 'poor', 'no', 'yes'],
       ...,
       [12.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [17.0, 60.0, 1.025, ..., 'good', 'no', 'no'],
       [58.0, 80.0, 1.025, ..., 'good', 'no', 'no']], dtype=object)

In [39]:
y=data.iloc[:,25:].values

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
lb=LabelEncoder()

In [42]:
x[:,5]=lb.fit_transform(x[:,5])

In [43]:
x

array([[48.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [7.0, 50.0, 1.02, ..., 'good', 'no', 'no'],
       [62.0, 80.0, 1.01, ..., 'poor', 'no', 'yes'],
       ...,
       [12.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [17.0, 60.0, 1.025, ..., 'good', 'no', 'no'],
       [58.0, 80.0, 1.025, ..., 'good', 'no', 'no']], dtype=object)

In [44]:
x[:,6]=lb.fit_transform(x[:,6])

In [45]:
x[:,7]=lb.fit_transform(x[:,7])

In [46]:

x[:,8]=lb.fit_transform(x[:,8])

In [47]:

x[:,18]=lb.fit_transform(x[:,18])

In [48]:
x[:,19]=lb.fit_transform(x[:,19])

In [49]:
x[:,20]=lb.fit_transform(x[:,20])

In [50]:
x[:,21]=lb.fit_transform(x[:,21])

In [51]:
x[:,22]=lb.fit_transform(x[:,22])

In [52]:
x[:,23]=lb.fit_transform(x[:,23])

In [53]:
y[:,0]=lb.fit_transform(y[:,0])

In [54]:

x[0:5,:]

array([[48.0, 80.0, 1.02, 1.0, 0.0, 1, 1, 0, 0, 121.0, 36.0, 1.2,
        137.52875399361022, 4.627243589743592, 15.4, 44.0, 7800.0, 5.2,
        1, 1, 0, 0, 0, 0],
       [7.0, 50.0, 1.02, 4.0, 0.0, 1, 1, 0, 0, 148.0365168539326, 18.0,
        0.8, 137.52875399361022, 4.627243589743592, 11.3, 38.0, 6000.0,
        5.2, 0, 0, 0, 0, 0, 0],
       [62.0, 80.0, 1.01, 2.0, 3.0, 1, 1, 0, 0, 423.0, 53.0, 1.8,
        137.52875399361022, 4.627243589743592, 9.6, 31.0, 7500.0, 5.2, 0,
        1, 0, 1, 0, 1],
       [48.0, 70.0, 1.005, 4.0, 0.0, 1, 0, 1, 0, 117.0, 56.0, 3.8, 111.0,
        2.5, 11.2, 32.0, 6700.0, 3.9, 1, 0, 0, 1, 1, 1],
       [51.0, 80.0, 1.01, 2.0, 0.0, 1, 1, 0, 0, 106.0, 26.0, 1.4,
        137.52875399361022, 4.627243589743592, 11.6, 35.0, 7300.0, 4.6,
        0, 0, 0, 0, 0, 0]], dtype=object)

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.35,random_state=1)

In [57]:
y_train =y_train.flatten()
y_test = y_test.flatten()

In [58]:


y_train = y_train.astype(np.float)
y_test = y_test.astype(np.float)


In [59]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [60]:
from joblib import dump
dump(sc,"scale.save")

['scale.save']

In [61]:
from sklearn.tree import DecisionTreeClassifier
dt= DecisionTreeClassifier(criterion='entropy',random_state=0)
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [62]:
import pickle
pickle.dump(dt,open('result.pkl','wb'))

In [63]:
pred=dt.predict(x_test)

In [64]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.9714285714285714